format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/accessom2_restart.nml
  hashes:
    binhash: da2be152610ee0215357e4963066d149
    md5: 98aa36cc316484335ffaa5883c8e62b2
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/grid.nc
  hashes:
    binhash: f74dec6d262065897673318f911952b0
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/i2o.nc
  hashes:
    binhash: 223ff8bac5a4f0275fb82ba1724d926b
    md5: 4d1eb5e27a20cadf722ebbc7872193ca
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/ice.restart_file
  hashes:
    binhash: 69cb57d852a6f941981b420d1cf08839
    md5: d69ddc4880bd96a50dadb385da860c29
work/ice/RESTART/iced.2549-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/iced.2549-01-01-00000.nc
  hashes:
    binhash: f7a1320b9ebc0e3ae2aa02e4a12cb722
    md5: a785ae69d713e420b6896d9583464805
work/ice/RESTART/iced.2550-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/iced.2550-01-01-00000.nc
  hashes:
    binhash: aab09994178c969f7dd794b87727f4af
    md5: 7c28c0f85fd4ba6ce924a60f94185645
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/kmt.nc
  hashes:
    binhash: 6d1c47c9f4018e8b9ba6de9a412bc445
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/mice.nc
  hashes:
    binhash: 0e3ca84d830c9eb8f1171bdce9bbcf7a
    md5: 81bb9d4ce5524952e10a4233ad1ce912
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/monthly_sstsss.nc
  hashes:
    binhash: d271b16ba496ddf5f07e6767c69b36ad
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/o2i.nc
  hashes:
    binhash: 1aaf16331637620f18cded39cbe69998
    md5: 65d81baeba65b4f19d3a8d83cb98b314
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/sicemass.nc
  hashes:
    binhash: 3c4759a480c831361458059a2582423c
    md5: 116526576dd29aad7413acc1fa1cded7
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ice/u_star.nc
  hashes:
    binhash: bd85cd17e74faa7783623bbb19a02c2f
    md5: ad99fbdb7723324aed0b0851469914ff
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_age.res.nc
  hashes:
    binhash: 20074547b42aa244860048be171e8132
    md5: 4b8483a8bf1a892ab35dfce18e0a851a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d35e7ed4305832233f00709750de7cd0
    md5: 61ed84897d655891081e620b51fb4916
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0c80926b53545ed50c1b325b6d8eb72e
    md5: e8703f8be174eb1bb20e90fb0555bbcb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_density.res.nc
  hashes:
    binhash: 59548b93dd1e380e7f33a25c11931a8d
    md5: 497d97e7a3fd16c6ebfa466d57bdbadf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 813258f26dfc94e69bafa5fc5606024d
    md5: a1ed83e4c48049e62101a9e700eec73b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e7906df74d2cb5f7d288bc061f8eeb95
    md5: f42f2a62284e1a3a8e77f325f94d97d8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c3075f0cc4e1cd6155ecf7893d5152b2
    md5: efe4772666309dc531400b2139de9a4a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 764fc5ba43eace96dddf305b9afb756f
    md5: fead9a1251187937655ffc701270b982
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_solo.res
  hashes:
    binhash: 5102e92e23d171bd884eb344576726c0
    md5: 1ffe6b54540edf14b826cd400f006064
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fb9f23f9cd3aa350a20ad67c2c5d108a
    md5: 9f68e9c588e7a9b108132985421dcd33
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6a607667adc805a42591b7c5a874ebfa
    md5: 8f776d4bdfa9b03615f37ce0be576704
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_tracer.res
  hashes:
    binhash: da8ab89a7f33cc5a1514591b4d10b0ad
    md5: 6c2ba1f378a9ac073591c62086e38a56
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 64442517b10ef23ab0c7f3058efe9d42
    md5: 0cef57bfee569b4549de674470d47140
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/mv7494/access-om2/archive/025deg_jra55_ryf_ENFull/restart324/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8eb4bcb3ea0b311f43e0cc2162654c48
    md5: effa5d870256fc21a669ddfe007f99c9
